now check

diff --git a/.github/workflows/CICD.yaml b/.github/workflows/CICD.yaml
--- a/.github/workflows/CICD.yaml
+++ b/.github/workflows/CICD.yaml
@@ -111,14 +111,16 @@ jobs:
           docker run --rm -v $(pwd):/zap/wrk:rw \
           -t owasp/zap2docker-stable zap-baseline.py \
           -t http://65.2.121.174:8082/ \
-          -r zap-report.html || true
-           echo "✓ ZAP scan completed"
+          -r /zap/wrk/zap-report.html || true
+          ls -lh zap-report.html || echo "Report not found"
+          echo "✓ ZAP scan completed"
 
       - name: uplaod ZAP report Artifact
         uses: actions/upload-artifact@v4
         with:
           name: zap-report
           path: zap-report.html
+          if-no-files-found: warn
 
 
   VIEW_ZAP_REPORT:
